FROM node:alpine

# Install Yarn.
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates \
    wget \
    tar && \
    cd /usr/local/bin && \
    wget https://yarnpkg.com/latest.tar.gz && \
    tar zvxf latest.tar.gz && \
    ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
    apk del .build-deps

EXPOSE <%= frontendPort %>

RUN mkdir -p /app
WORKDIR /app

COPY package.json ./
RUN yarn

COPY . .

RUN npm run build
CMD ["npm", "start"]
